### ISSUE TITLE
External data strategy needs decided! 

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/p2lab-pokemon#43]
We're about to start needing external data sources. E.g., the Pokédex. Do we want to say that everything needs to be run from the root directory. Or do we want to support the library being more portable? If the later then we need to configure how `pip install` will setup and copy across data files.

@phinate how would you like this done? 

--- 
Examples of data needed to be usable by the library:
- https://github.com/AoifeHughes/poke-env/tree/b882c626b1382f1cda67aaee50fff9a4cc7eedb4/src/poke_env/data/static

**Comment by hsahovic** [comment]
No, not yet. The data is included in the `static` folder though.

You could add it through something like:

```python
def load_learnsets(self) -> Dict[str, Dict[str, Union[int, float]]]:
        with open(os.path.join(self._static_files_root, "learnsets.json")) as f:
            return orjson.loads(f.read())
```

and adding `learnsets` in `GenData`'s init - if you want to open a PR to `poke-env` I would happily merge it.

**Comment by AoifeHughes** [comment]
Good shout! Yeah I'll do that. Thanks!

**Comment by AoifeHughes** [comment]
Think this is done with recent PR #44
